name: 'Asciidoctor Github Action'
author: 'Eirik Ola Aksnes'
description: 'Use asciidoctor in Github actions'

branding:
  icon: 'file'
  color: 'green'
inputs:
    program:
        description: 'asciidoctor'
        required: false
        default: 'RUN'
    entry_point:
        description: 'Specify if entry point is other than default. E.g README'
        required: false
        default: 'index'
    docs_folder:
        description: 'Specify if docs folder is other than default. E.g ./'
        required: false
        default: 'docs'
    include_unsupported_files:
        description: 'Toggle whether unsupported files should be included int the result or not'
        required: false
        default: 'false'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.program }}
        - ${{ inputs.entry_point }}
        - ${{ inputs.docs_folder }}
        - ${{ inputs.include_unsupported_files }}
outputs:
    time:
        description: 'Action Completed'
