name: 'Asciidoctor Github Action'
author: 'Eirik Ola Aksnes'
description: 'Use asciidoctor in Github actions'

branding:
  icon: 'file'
  color: 'green'
inputs:
    program:
        description: 'asciidoctor'
        required: false
        default: 'RUN'
    entry_point:
        description: 'Specify if entry point name is other than index, set it here. E.g README'
        required: false
        default: 'index'
    docs_folder:
        description: 'Specify if docs folder is other than docs, set it here. E.g ./ for root'
        required: false
        default: 'docs'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.program }}
        - ${{ inputs.entry_point }}
        - ${{ inputs.docs_folder }}
outputs:
    time:
        description: 'Action Completed'
