name: build adocs

on:
  push:
    branches:
    - main
    - master
    - alternative-entry-point-as-input

jobs:
  deploy-docs:
    runs-on: ubuntu-18.04
    name: Build and deploy docs to Github pages
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create docs build directory
      run: mkdir dist && chmod 777 dist
    - name: Build docs
      id: adocbuild
      uses: ./
      with: 
        main_entry_point_file: ./index.adoc
    - name: Deploy docs to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
